sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"

env:
    - PEP8_IGNORE="E731,W503,E402"

# command to install dependencies
install:
    - pip install coverage pep8 pytest

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
    - export MAJOR_PYTHON_VERSION=`echo $TRAVIS_PYTHON_VERSION | cut -c 1`
    - coverage run --source=toolz $(which nosetests)
                   --with-doctest toolz/
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage report --show-missing --fail-under=100 ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pep8 --ignore=$PEP8_IGNORE --exclude=conf.py,tests,examples,bench -r --show-source . ; fi
    # For convenience, make sure simple test commands work
    - py.test
    - nosetests

# load coverage status to https://coveralls.io
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls --use-mirrors ; coveralls ; fi

notifications:
  email: false
