sudo: false
language: python
python:
    - "3.5"
    - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
    include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: "pypy3.5-7.0"
      dist: xenial
      sudo: true
    - python: "pypy3.6-7.1.1"
      dist: xenial
      sudo: true

env:
    - PEP8_IGNORE="E731,W503,E402"

# command to install dependencies
install:
    - pip install coverage pep8 pytest

# command to run tests
# require 100% coverage (not including test files) to pass Travis CI test
# To skip pypy: - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then DOSTUFF ; fi
script:
    - export MAJOR_PYTHON_VERSION=`echo $TRAVIS_PYTHON_VERSION | cut -c 1`
    - coverage run --source=toolz $(which nosetests)
                   --with-doctest toolz/
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage report --show-missing --fail-under=100 ; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pep8 --ignore=$PEP8_IGNORE --exclude=conf.py,tests,examples,bench -r --show-source . ; fi
    # For convenience, make sure simple test commands work
    - python setup.py develop
    - py.test
    - nosetests

# load coverage status to https://coveralls.io
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls --use-mirrors ; coveralls ; fi

notifications:
  email: false
